"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback, useState } from "react";
import { SignInModal, type AuthView } from "@/components/SignInModal";

const Arrow = () => <span aria-hidden="true">→</span>;
const rows = [["Receive", "+ 50.00", "Settled"], ["Send", "- 12.50", "Settled"], ["Buy", "+ 100.00", "Settled"]];
function Brand() { return <Link className="v0Brand" href="/" aria-label="ABC Pay home"><Image src="/images/abc-logo.png" alt="" width={32} height={32} /><span><strong>ABC Pay</strong><small>by Africa’s Blockchain Club</small></span></Link>; }
function PaymentCard() { return <div className="v0PaymentCard"><div className="v0PaymentHead"><Brand /></div><div className="v0PaymentBody"><label>AMOUNT TO RECEIVE</label><div className="v0Amount"><span>R</span><strong>500</strong><small>ZAR</small></div><div className="v0Quote"><div><span>Customer pays</span><b>≈ 27.14 USDC</b></div><div><span>Network</span><b>Polygon</b></div><div><span>Quote validity</span><b>2 minutes</b></div></div><Link className="v0Primary v0Full" href="/merchant/qr-generate">▦ Generate payment QR</Link></div></div>; }
function Header({ initialView }: { initialView?: AuthView }) { const [view, setView] = useState<AuthView | null>(initialView ?? null); const close = useCallback(() => setView(null), []); return <><header className="v0Header v0Content"><Brand /><nav><a href="#how">How it works</a><a href="#merchants">For merchants</a><a href="#customers">For customers</a><a href="#security">Security</a></nav><div><button className="v0Text" onClick={() => setView("individual")}>Sign in</button><button className="v0Create" onClick={() => setView("register")}>Create account <Arrow /></button></div></header>{view && <SignInModal key={view} open initialView={view} onClose={close} />}</>; }
export default function AbcPayLanding({ initialView }: { initialView?: AuthView }) { const [view, setView] = useState<AuthView | null>(null); const close = useCallback(() => setView(null), []); return <div className="v0Landing"><Header initialView={initialView} /><main><section className="v0Hero v0Content"><div className="v0Copy"><p className="v0Context">A payment layer by Africa’s Blockchain Club</p><h1>Accept stablecoins.<br /><em>Receive rand.</em></h1><p>ABC Pay gives South African businesses a simple way to accept stablecoin payments and settle their sales in ZAR — no crypto expertise required.</p><div className="v0Actions"><button className="v0Primary" onClick={() => setView("register")}>Start accepting payments <Arrow /></button><a className="v0Secondary" href="#how">See how it works</a></div><div className="v0Proof"><span>Settle in ZAR</span><span>Track payments live</span><span>Stablecoin enabled</span></div></div><PaymentCard /></section><section className="v0Trust"><div className="v0Content">{[["01","Built for South Africa","Receive the money you use every day."],["02","Stablecoin payments","Accept USDC without price volatility."],["03","Live payment tracking","Know what has cleared, instantly."],["04","Built for the next economy","Modern rails, familiar settlement."]].map(([n,t,c]) => <div key={n}><b>{n}</b><strong>{t}</strong><span>{c}</span></div>)}</div></section><section id="how" className="v0Steps v0Content"><div className="v0Kicker">HOW IT WORKS</div><h2>Four steps from payment request<br />to ZAR.</h2><div>{[["01","Create a request","Set the amount in rand and share a payment QR with your customer."],["02","Customer pays","Your customer pays in USDC on a supported network."],["03","Confirm payment","ABC Pay watches the chain and confirms the transaction."],["04","Receive rand","Your settled amount is ready for your business."]].map(([n,t,c]) => <article key={n}><b>{n}</b><h3>{t}</h3><p>{c}</p></article>)}</div></section><section id="merchants" className="v0Merchant"><div className="v0Content"><div><div className="v0Kicker">FOR MERCHANTS</div><h2>Crypto payments without the crypto complexity.</h2><p>Keep serving customers while we handle the blockchain layer behind the scenes.</p><ul><li>✓ Customer pays by QR code</li><li>✓ Receive ZAR settlement</li><li>✓ Review a clean transaction history</li><li>✓ Prepare for real settlement</li></ul></div><div className="v0Mini"><div><b>Recent dashboard</b><span>Live</span></div><section><small>Available to settle</small><strong>R 12,450.00</strong></section>{rows.map(([t,a,s]) => <p key={t}><span>{t}</span><b>{a} USDC</b><i>{s}</i></p>)}</div></div></section></main><footer className="v0Footer v0Content"><Brand /><span>ABC Pay is a prototype for Africa’s Blockchain Club.</span><Link href="/wallet">Open wallet dashboard <Arrow /></Link></footer>{view && <SignInModal key={view} open initialView={view} onClose={close} />}</div>; }
